spring:
  application:
    name: mifss-app-bio
  profiles:
    active: @cloud.provider@

server:
  port: 8080

# Swagger 配置
swagger:
  title: MIFSS BIO API
  description: MIFSS 生物特征识别服务 API 文档
  version: "1.0"
