server:
  port: 8802

spring:
  application:
    name: mifss-app-ipt
  profiles:
    active: @cloud.provider@

# Swagger 配置
swagger:
  title: MIFSS IPT API
  description: MIFSS 住院服务 API 文档
  version: "1.0"
