server:
  port: 8802
  servlet:
    context-path: /mifss/ipt

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/medicare_202588?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mifss:
  cloud:
    provider: aliyun
    storage: oss
    database: rds
    message-queue: rocketmq

# Dubbo3 配置 (服务消费方)
dubbo:
  application:
    name: ${spring.application.name}
    qos-port: 22223
    qos-enable: true
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: nacos://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
  consumer:
    check: false
    timeout: 10000
  scan:
    base-packages: com.aeye.mifss
